"""
React/Next.js + Apache ECharts app generator for Snowflake App Runtime (SPCS).

Generates a complete Next.js 14 project scaffold ready for deployment via
`snow app deploy` using the snowflake-apps + sar-actions-desktop skills.

Charts use Apache ECharts (echarts-for-react) — enterprise-grade animations,
drill-down, cross-chart highlighting, and dark-mode support out of the box.
"""

from __future__ import annotations

import json
import os
import re
import textwrap
from pathlib import Path
from typing import Any

from .chart_mappings import echarts_component_name
from .heuristics import infer_filter_widgets

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def _safe_var(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", name)


def _field_list(fields_by_ds: dict) -> list[str]:
    out: list[str] = []
    for vals in fields_by_ds.values():
        for v in vals:
            out.append(v if isinstance(v, str) else v.get("name", ""))
    return [f for f in out if f]


# ---------------------------------------------------------------------------
# Static file generators
# ---------------------------------------------------------------------------

def _gen_app_yml(app_name: str) -> str:
    safe = _slugify(app_name).replace("-", "_").upper()
    return textwrap.dedent(f"""\
        version: 2

        name: {safe}_APP
        title: "{app_name}"
        description: "Enterprise BI dashboard generated by bi-modernization skill."

        services:
          - name: frontend
            spec:
              type: nextjs
              port: 3000
              env:
                NEXT_PUBLIC_APP_NAME: "{app_name}"
    """)


def _gen_package_json(app_name: str) -> str:
    safe = _slugify(app_name)
    return json.dumps({
        "name": safe,
        "version": "1.0.0",
        "private": True,
        "scripts": {
            "dev": "next dev",
            "build": "next build",
            "start": "next start",
            "lint": "next lint",
        },
        "dependencies": {
            "next": "14.2.4",
            "react": "^18.3.1",
            "react-dom": "^18.3.1",
            "echarts": "^5.5.0",
            "echarts-for-react": "^3.0.2",
            "clsx": "^2.1.1",
            "date-fns": "^3.6.0",
        },
        "devDependencies": {
            "typescript": "^5.5.2",
            "@types/node": "^20.14.9",
            "@types/react": "^18.3.3",
            "@types/react-dom": "^18.3.0",
            "tailwindcss": "^3.4.4",
            "postcss": "^8.4.38",
            "autoprefixer": "^10.4.19",
            "eslint": "^8.57.0",
            "eslint-config-next": "14.2.4",
        },
    }, indent=2)


def _gen_tailwind_config() -> str:
    return textwrap.dedent("""\
        import type { Config } from 'tailwindcss'

        const config: Config = {
          content: [
            './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
            './src/components/**/*.{js,ts,jsx,tsx,mdx}',
            './src/app/**/*.{js,ts,jsx,tsx,mdx}',
          ],
          theme: {
            extend: {
              colors: {
                snowflake: {
                  blue:     '#29B5E8',
                  darkblue: '#11567F',
                  navy:     '#003865',
                  sky:      '#00A4EF',
                  teal:     '#1ED7AA',
                },
              },
              fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
              },
            },
          },
          plugins: [],
        }
        export default config
    """)


def _gen_tsconfig() -> str:
    return json.dumps({
        "compilerOptions": {
            "target": "ES2017",
            "lib": ["dom", "dom.iterable", "esnext"],
            "allowJs": True,
            "skipLibCheck": True,
            "strict": True,
            "noEmit": True,
            "esModuleInterop": True,
            "module": "esnext",
            "moduleResolution": "bundler",
            "resolveJsonModule": True,
            "isolatedModules": True,
            "jsx": "preserve",
            "incremental": True,
            "plugins": [{"name": "next"}],
            "paths": {"@/*": ["./src/*"]},
        },
        "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        "exclude": ["node_modules"],
    }, indent=2)


def _gen_globals_css() -> str:
    return textwrap.dedent("""\
        @tailwind base;
        @tailwind components;
        @tailwind utilities;

        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');

        :root {
          --sf-blue: #29B5E8;
          --sf-dark: #11567F;
          --sf-navy: #003865;
        }

        * { box-sizing: border-box; }
        body { font-family: 'Inter', system-ui, sans-serif; background: #F8FAFC; }

        .chart-card {
          background: #fff;
          border: 1px solid #E2E8F0;
          border-radius: 12px;
          padding: 20px;
          box-shadow: 0 1px 3px rgba(0,0,0,.06);
        }

        .metric-card {
          background: linear-gradient(135deg, #11567F 0%, #29B5E8 100%);
          border-radius: 12px;
          padding: 20px;
          color: #fff;
        }
    """)


def _gen_snowflake_lib() -> str:
    return textwrap.dedent("""\
        /**
         * Snowflake query helper for Snowflake App Runtime.
         * Uses the injected window.__SNOWFLAKE_HOST__ and PAT/session token.
         */

        declare const window: Window & {
          __SNOWFLAKE_HOST__?: string;
          __SNOWFLAKE_TOKEN__?: string;
        };

        const getHost = (): string =>
          window.__SNOWFLAKE_HOST__ ??
          process.env.NEXT_PUBLIC_SNOWFLAKE_HOST ??
          "";

        const getToken = (): string =>
          window.__SNOWFLAKE_TOKEN__ ??
          process.env.NEXT_PUBLIC_SNOWFLAKE_TOKEN ??
          "";

        export async function query<T = Record<string, unknown>>(
          sql: string
        ): Promise<T[]> {
          const host = getHost();
          if (!host) {
            // Development mode: return empty dataset
            console.warn("[snowflake] No host configured — returning empty result.");
            return [];
          }

          const res = await fetch(`https://${host}/api/v2/statements`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${getToken()}`,
              "X-Snowflake-Authorization-Token-Type": "KEYPAIR_JWT",
            },
            body: JSON.stringify({
              statement: sql,
              timeout: 30,
              resultSetMetaData: { format: "jsonv2" },
            }),
          });

          if (!res.ok) {
            const err = await res.text();
            throw new Error(`Snowflake query failed: ${err}`);
          }

          const data = await res.json();
          const cols: string[] = (data.resultSetMetaData?.rowType ?? []).map(
            (c: { name: string }) => c.name
          );
          return (data.data ?? []).map((row: unknown[]) =>
            Object.fromEntries(cols.map((c, i) => [c, row[i]])) as T
          );
        }


        export async function callAgent(
          agentFqn: string,
          message: string
        ): Promise<string> {
          const host = getHost();
          if (!host) return "Agent not available in development mode.";

          const res = await fetch(`https://${host}/api/v2/cortex/agent:run`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              Authorization: `Bearer ${getToken()}`,
            },
            body: JSON.stringify({
              agent: agentFqn,
              messages: [{ role: "user", content: message }],
              stream: false,
            }),
          });

          if (!res.ok) return `Agent error: ${await res.text()}`;
          const data = await res.json();
          return data?.choices?.[0]?.message?.content ?? "No response.";
        }
    """)


def _gen_types() -> str:
    return textwrap.dedent("""\
        export interface ChartData {
          [key: string]: string | number | null;
        }

        export interface DashboardMeta {
          name: string;
          slug: string;
          sheetCount: number;
        }

        export interface FilterState {
          [fieldName: string]: string | string[] | [Date, Date] | null;
        }
    """)


# ---------------------------------------------------------------------------
# Reusable chart components (ECharts)
# ---------------------------------------------------------------------------

def _gen_bar_chart_tsx() -> str:
    return textwrap.dedent("""\
        "use client";
        import ReactECharts from "echarts-for-react";
        import { ChartData } from "@/lib/types";

        interface Props {
          data: ChartData[];
          xField: string;
          yField: string;
          title?: string;
          horizontal?: boolean;
          stacked?: boolean;
          color?: string[];
        }

        const SF_COLORS = ["#29B5E8","#11567F","#00A4EF","#1ED7AA","#003865","#6DD0F0","#0076BE","#5EC6E8"];

        export default function BarChart({ data, xField, yField, title, horizontal, stacked, color }: Props) {
          const option = {
            color: color ?? SF_COLORS,
            title: title ? { text: title, textStyle: { fontSize: 14, fontWeight: 600, color: "#1E293B" } } : undefined,
            tooltip: { trigger: "axis", axisPointer: { type: "shadow" } },
            grid: { left: "3%", right: "4%", bottom: "3%", containLabel: true },
            xAxis: horizontal
              ? { type: "value", axisLine: { show: false }, splitLine: { lineStyle: { color: "#F1F5F9" } } }
              : { type: "category", data: data.map(d => d[xField]), axisTick: { show: false }, axisLine: { lineStyle: { color: "#CBD5E1" } } },
            yAxis: horizontal
              ? { type: "category", data: data.map(d => d[xField]), axisTick: { show: false } }
              : { type: "value", axisLine: { show: false }, splitLine: { lineStyle: { color: "#F1F5F9" } } },
            series: [{
              type: "bar",
              data: data.map(d => d[yField]),
              stack: stacked ? "total" : undefined,
              barMaxWidth: 40,
              itemStyle: { borderRadius: [4, 4, 0, 0] },
              emphasis: { itemStyle: { shadowBlur: 8, shadowColor: "rgba(41,181,232,.4)" } },
            }],
          };
          return <ReactECharts option={option} style={{ height: 320 }} />;
        }
    """)


def _gen_line_chart_tsx() -> str:
    return textwrap.dedent("""\
        "use client";
        import ReactECharts from "echarts-for-react";
        import { ChartData } from "@/lib/types";

        interface Props {
          data: ChartData[];
          xField: string;
          yField: string;
          title?: string;
          area?: boolean;
          smooth?: boolean;
        }

        const SF_COLORS = ["#29B5E8","#11567F","#00A4EF","#1ED7AA","#003865","#6DD0F0"];

        export default function LineChart({ data, xField, yField, title, area, smooth = true }: Props) {
          const option = {
            color: SF_COLORS,
            title: title ? { text: title, textStyle: { fontSize: 14, fontWeight: 600, color: "#1E293B" } } : undefined,
            tooltip: { trigger: "axis" },
            grid: { left: "3%", right: "4%", bottom: "3%", containLabel: true },
            xAxis: {
              type: "category",
              data: data.map(d => d[xField]),
              boundaryGap: false,
              axisTick: { show: false },
              axisLine: { lineStyle: { color: "#CBD5E1" } },
            },
            yAxis: {
              type: "value",
              axisLine: { show: false },
              splitLine: { lineStyle: { color: "#F1F5F9" } },
            },
            series: [{
              type: "line",
              data: data.map(d => d[yField]),
              smooth,
              symbol: "circle",
              symbolSize: 6,
              lineStyle: { width: 2 },
              areaStyle: area ? {
                color: { type: "linear", x: 0, y: 0, x2: 0, y2: 1,
                  colorStops: [
                    { offset: 0, color: "rgba(41,181,232,.25)" },
                    { offset: 1, color: "rgba(41,181,232,.02)" },
                  ],
                },
              } : undefined,
              emphasis: { scale: true },
            }],
          };
          return <ReactECharts option={option} style={{ height: 320 }} />;
        }
    """)


def _gen_pie_chart_tsx() -> str:
    return textwrap.dedent("""\
        "use client";
        import ReactECharts from "echarts-for-react";
        import { ChartData } from "@/lib/types";

        interface Props {
          data: ChartData[];
          nameField: string;
          valueField: string;
          title?: string;
          donut?: boolean;
        }

        const SF_COLORS = ["#29B5E8","#11567F","#00A4EF","#1ED7AA","#003865","#6DD0F0","#0076BE","#5EC6E8"];

        export default function PieChart({ data, nameField, valueField, title, donut }: Props) {
          const option = {
            color: SF_COLORS,
            title: title ? { text: title, left: "center", textStyle: { fontSize: 14, fontWeight: 600, color: "#1E293B" } } : undefined,
            tooltip: { trigger: "item", formatter: "{b}: {c} ({d}%)" },
            legend: { orient: "vertical", left: "left", textStyle: { color: "#64748B" } },
            series: [{
              type: "pie",
              radius: donut ? ["40%", "70%"] : "60%",
              center: ["55%", "55%"],
              data: data.map(d => ({ name: d[nameField], value: d[valueField] })),
              emphasis: {
                itemStyle: { shadowBlur: 10, shadowOffsetX: 0, shadowColor: "rgba(0,0,0,.15)" },
              },
              label: { formatter: "{b}\n{d}%", color: "#475569" },
            }],
          };
          return <ReactECharts option={option} style={{ height: 340 }} />;
        }
    """)


def _gen_scatter_chart_tsx() -> str:
    return textwrap.dedent("""\
        "use client";
        import ReactECharts from "echarts-for-react";
        import { ChartData } from "@/lib/types";

        interface Props {
          data: ChartData[];
          xField: string;
          yField: string;
          title?: string;
          colorField?: string;
        }

        export default function ScatterChart({ data, xField, yField, title }: Props) {
          const option = {
            color: ["#29B5E8"],
            title: title ? { text: title, textStyle: { fontSize: 14, fontWeight: 600, color: "#1E293B" } } : undefined,
            tooltip: { trigger: "item", formatter: (p: { data: number[] }) => `${p.data[0]}, ${p.data[1]}` },
            grid: { left: "3%", right: "4%", bottom: "3%", containLabel: true },
            xAxis: { type: "value", splitLine: { lineStyle: { color: "#F1F5F9" } } },
            yAxis: { type: "value", splitLine: { lineStyle: { color: "#F1F5F9" } } },
            series: [{
              type: "scatter",
              data: data.map(d => [d[xField], d[yField]]),
              symbolSize: 10,
              itemStyle: { color: "#29B5E8", opacity: 0.75 },
            }],
          };
          return <ReactECharts option={option} style={{ height: 320 }} />;
        }
    """)


def _gen_area_chart_tsx() -> str:
    return textwrap.dedent("""\
        "use client";
        import LineChart from "./LineChart";
        import { ChartData } from "@/lib/types";

        interface Props {
          data: ChartData[];
          xField: string;
          yField: string;
          title?: string;
        }

        /** Area chart is a line chart with areaStyle=true */
        export default function AreaChart({ data, xField, yField, title }: Props) {
          return <LineChart data={data} xField={xField} yField={yField} title={title} area smooth />;
        }
    """)


def _gen_metric_card_tsx() -> str:
    return textwrap.dedent("""\
        interface Props {
          label: string;
          value: string | number;
          subvalue?: string;
          trend?: string;
          trendUp?: boolean;
        }

        export default function MetricCard({ label, value, subvalue, trend, trendUp }: Props) {
          return (
            <div className="metric-card">
              <p className="text-sm font-medium text-blue-100 mb-1">{label}</p>
              <p className="text-3xl font-bold text-white">{value}</p>
              {subvalue && <p className="text-sm text-blue-200 mt-1">{subvalue}</p>}
              {trend && (
                <p className={`text-sm mt-2 font-medium ${trendUp ? "text-green-300" : "text-red-300"}`}>
                  {trendUp ? "▲" : "▼"} {trend}
                </p>
              )}
            </div>
          );
        }
    """)


def _gen_data_table_tsx() -> str:
    return textwrap.dedent("""\
        "use client";

        interface Props {
          data: Record<string, unknown>[];
          title?: string;
        }

        export default function DataTable({ data, title }: Props) {
          if (!data.length) return <p className="text-slate-400 text-sm">No data.</p>;
          const cols = Object.keys(data[0]);
          return (
            <div>
              {title && <h3 className="text-sm font-semibold text-slate-700 mb-2">{title}</h3>}
              <div className="overflow-x-auto rounded-lg border border-slate-200">
                <table className="min-w-full text-sm">
                  <thead className="bg-slate-50 border-b border-slate-200">
                    <tr>
                      {cols.map(c => (
                        <th key={c} className="px-4 py-2 text-left font-semibold text-slate-600">{c}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {data.map((row, i) => (
                      <tr key={i} className={i % 2 === 0 ? "bg-white" : "bg-slate-50"}>
                        {cols.map(c => (
                          <td key={c} className="px-4 py-2 text-slate-700">{String(row[c] ?? "")}</td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          );
        }
    """)


def _gen_charts_index() -> str:
    return textwrap.dedent("""\
        export { default as BarChart }     from "./BarChart";
        export { default as LineChart }    from "./LineChart";
        export { default as AreaChart }    from "./AreaChart";
        export { default as PieChart }     from "./PieChart";
        export { default as ScatterChart } from "./ScatterChart";
        export { default as MetricCard }   from "./MetricCard";
        export { default as DataTable }    from "./DataTable";
    """)


def _gen_filter_panel_tsx(filter_widgets: list[dict]) -> str:
    """Generate a sidebar FilterPanel component."""
    widget_jsx_lines: list[str] = []
    for w in filter_widgets:
        name = w["field_name"]
        label = w["label"]
        var = _safe_var(name)
        wtype = w["widget_type"]

        if wtype == "date_range":
            widget_jsx_lines.append(textwrap.dedent(f"""\
                      <div>
                        <label className="block text-xs font-medium text-slate-500 mb-1">{label}</label>
                        <input type="date" className="w-full border border-slate-200 rounded px-2 py-1 text-sm"
                          onChange={{e => onChange({{ {var}: e.target.value }})}} />
                      </div>
            """))
        else:
            widget_jsx_lines.append(textwrap.dedent(f"""\
                      <div>
                        <label className="block text-xs font-medium text-slate-500 mb-1">{label}</label>
                        <select className="w-full border border-slate-200 rounded px-2 py-1 text-sm"
                          onChange={{e => onChange({{ {var}: e.target.value }})}}>
                          <option value="">All</option>
                        </select>
                      </div>
            """))

    widgets_str = "\n".join(widget_jsx_lines) if widget_jsx_lines else \
        '          <p className="text-xs text-slate-400">No filters available.</p>'

    return textwrap.dedent(f"""\
        "use client";
        import {{ FilterState }} from "@/lib/types";

        interface Props {{
          onChange: (updates: Partial<FilterState>) => void;
        }}

        export default function FilterPanel({{ onChange }}: Props) {{
          return (
            <aside className="w-56 bg-white border-r border-slate-200 p-4 flex flex-col gap-3">
              <h2 className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Filters</h2>
        {widgets_str}
            </aside>
          );
        }}
    """)


def _gen_agent_chat_tsx(agent_fqn: str) -> str:
    return textwrap.dedent(f"""\
        "use client";
        import {{ useState }} from "react";
        import {{ callAgent }} from "@/lib/snowflake";

        export default function AgentChat() {{
          const [open, setOpen] = useState(false);
          const [query, setQuery] = useState("");
          const [response, setResponse] = useState("");
          const [loading, setLoading] = useState(false);

          const ask = async () => {{
            if (!query.trim()) return;
            setLoading(true);
            setResponse("");
            try {{
              const answer = await callAgent("{agent_fqn}", query);
              setResponse(answer);
            }} finally {{
              setLoading(false);
            }}
          }};

          return (
            <>
              {{/* Floating chat button */}}
              <button
                onClick={{() => setOpen(!open)}}
                className="fixed bottom-6 right-6 w-12 h-12 rounded-full bg-snowflake-blue text-white shadow-lg flex items-center justify-center text-xl z-50 hover:bg-snowflake-darkblue transition-colors"
                title="Ask your data"
              >
                ✦
              </button>

              {{/* Chat drawer */}}
              {{open && (
                <div className="fixed bottom-20 right-6 w-80 bg-white rounded-2xl shadow-2xl border border-slate-200 z-50 flex flex-col overflow-hidden">
                  <div className="bg-snowflake-blue px-4 py-3 flex items-center justify-between">
                    <span className="text-white font-semibold text-sm">Ask your data</span>
                    <button onClick={{() => setOpen(false)}} className="text-white opacity-70 hover:opacity-100">✕</button>
                  </div>
                  <div className="p-3 flex flex-col gap-2 flex-1">
                    <textarea
                      className="w-full border border-slate-200 rounded-lg px-3 py-2 text-sm resize-none h-20 focus:outline-none focus:ring-2 focus:ring-snowflake-blue"
                      placeholder="Ask a question in plain English..."
                      value={{query}}
                      onChange={{e => setQuery(e.target.value)}}
                    />
                    <button
                      onClick={{ask}}
                      disabled={{loading}}
                      className="bg-snowflake-blue text-white rounded-lg py-2 text-sm font-medium hover:bg-snowflake-darkblue disabled:opacity-50 transition-colors"
                    >
                      {{loading ? "Thinking…" : "Ask"}}
                    </button>
                    {{response && (
                      <div className="text-sm text-slate-700 bg-slate-50 rounded-lg p-3 leading-relaxed whitespace-pre-wrap">
                        {{response}}
                      </div>
                    )}}
                  </div>
                </div>
              )}}
            </>
          );
        }}
    """)


def _gen_layout_tsx(app_name: str, dashboard_names: list[str], embed_agent: str | None) -> str:
    nav_links = "\n".join(
        f'            <a href="/dashboard/{_slugify(n)}" '
        f'className="block px-3 py-2 rounded-lg text-sm text-slate-300 hover:bg-slate-700 hover:text-white transition-colors">'
        f'{n}</a>'
        for n in dashboard_names
    )
    agent_import = 'import AgentChat from "@/components/AgentChat";\n' if embed_agent else ""
    agent_tag = "      <AgentChat />\n" if embed_agent else ""

    return textwrap.dedent(f"""\
        import type {{ Metadata }} from "next";
        import "./globals.css";
        {agent_import}
        export const metadata: Metadata = {{
          title: "{app_name}",
          description: "Enterprise BI dashboard powered by Snowflake",
        }};

        export default function RootLayout({{ children }}: {{ children: React.ReactNode }}) {{
          return (
            <html lang="en">
              <body className="flex h-screen overflow-hidden bg-slate-50">
                {{/* Sidebar navigation */}}
                <nav className="w-52 bg-slate-800 flex flex-col shrink-0">
                  <div className="px-4 py-5 border-b border-slate-700">
                    <p className="text-white font-semibold text-sm">{app_name}</p>
                    <p className="text-slate-400 text-xs mt-0.5">Analytics Suite</p>
                  </div>
                  <div className="flex-1 overflow-y-auto p-3 space-y-1">
        {nav_links}
                  </div>
                  <div className="p-3 border-t border-slate-700">
                    <p className="text-xs text-slate-500 text-center">Powered by Snowflake</p>
                  </div>
                </nav>

                {{/* Main content */}}
                <main className="flex-1 overflow-y-auto">
                  {{children}}
                </main>

        {agent_tag}
              </body>
            </html>
          );
        }}
    """)


def _gen_home_page_tsx(dashboard_names: list[str]) -> str:
    cards = "\n".join(
        f'        <a href="/dashboard/{_slugify(n)}" '
        f'className="chart-card hover:shadow-md transition-shadow cursor-pointer block">'
        f'<p className="font-semibold text-slate-800">{n}</p>'
        f'<p className="text-sm text-slate-500 mt-1">View dashboard →</p></a>'
        for n in dashboard_names
    )
    return textwrap.dedent(f"""\
        export default function Home() {{
          return (
            <div className="p-8">
              <h1 className="text-2xl font-bold text-slate-900 mb-2">Dashboards</h1>
              <p className="text-slate-500 mb-8">Select a dashboard to explore.</p>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {cards}
              </div>
            </div>
          );
        }}
    """)


def _gen_dashboard_page_tsx(
    dashboard: dict,
    inventory: dict,
    table_name: str,
    semantic_view: str | None,
) -> str:
    """Generate a Next.js page for one dashboard."""
    name = dashboard.get("name", "Dashboard")
    # Normalize: sheets may be plain strings (zone names with no field metadata)
    # or full dicts produced by extract_dashboard_field_usage.  Always work with dicts.
    sheets = [
        s if isinstance(s, dict) else {"name": s, "fields_by_datasource": {}}
        for s in dashboard.get("sheets", [])
    ]

    dims = inventory.get("dimensions", [])
    measures = (inventory.get("measures", []) +
                inventory.get("metrics", []) +
                inventory.get("facts", []))

    raw_filters = inventory.get("parameters", []) or inventory.get("filters", [])
    filter_widgets = infer_filter_widgets(raw_filters) if raw_filters else []

    query_target = semantic_view or table_name or "DB.SCHEMA.TABLE -- TODO: replace"

    imports = {
        "BarChart", "LineChart", "AreaChart", "PieChart",
        "ScatterChart", "MetricCard", "DataTable"
    }
    used_components: set[str] = set()

    chart_blocks: list[str] = []

    for i, sheet in enumerate(sheets):
        sname = sheet.get("name", f"Sheet {i+1}")
        chart_type = sheet.get("chart_type_echarts") or sheet.get("chart_type_plotly") or "bar"
        component = echarts_component_name(chart_type)

        if component is None or chart_type == "filter":
            continue  # filter slicers go into FilterPanel

        used_components.add(component)

        # Field resolution (simplified)
        sheet_fields = []
        for vals in sheet.get("fields_by_datasource", {}).values():
            sheet_fields.extend(vals if isinstance(vals[0] if vals else None, str) else
                                 [v.get("name", "") if isinstance(v, dict) else v for v in vals])

        dim_names = [d["name"] for d in dims if d.get("name") in sheet_fields][:2]
        meas_names = [m["name"] for m in measures if m.get("name") in sheet_fields][:1]
        if not dim_names and dims:
            dim_names = [dims[0]["name"]]
        if not meas_names and measures:
            meas_names = [measures[0]["name"]]

        x_field = (dim_names[0].upper() if dim_names else "CATEGORY")
        y_field = (meas_names[0].upper() if meas_names else "VALUE")

        state_var = f"data{i}"
        sql = (
            f'SELECT "{x_field}", SUM("{y_field}") AS "{y_field}" '
            f'FROM {query_target} GROUP BY "{x_field}" '
            f'ORDER BY "{y_field}" DESC LIMIT 200'
        )

        props_map = {
            "BarChart":    f'data={{{state_var}}} xField="{x_field}" yField="{y_field}" title="{sname}"',
            "LineChart":   f'data={{{state_var}}} xField="{x_field}" yField="{y_field}" title="{sname}"',
            "AreaChart":   f'data={{{state_var}}} xField="{x_field}" yField="{y_field}" title="{sname}"',
            "PieChart":    f'data={{{state_var}}} nameField="{x_field}" valueField="{y_field}" title="{sname}"',
            "ScatterChart":f'data={{{state_var}}} xField="{x_field}" yField="{y_field}" title="{sname}"',
            "MetricCard":  f'label="{sname}" value={{String({state_var}[0]?.["{y_field}"] ?? 0)}}',
            "DataTable":   f'data={{{state_var}}} title="{sname}"',
        }

        chart_blocks.append(textwrap.dedent(f"""\
              {{/* {sname} */}}
              <div className="chart-card">
                <{component} {props_map.get(component, "")} />
              </div>
        """))

    # State initialisation
    state_inits = "\n".join(
        f'  const [data{i}, setData{i}] = useState<Record<string,unknown>[]>([]);'
        for i in range(len(chart_blocks))
    )

    # Data fetch hooks
    sql_list = []
    for i, sheet in enumerate(sheets):
        dim_names = []
        meas_names = []
        for vals in sheet.get("fields_by_datasource", {}).values():
            for v in vals:
                n = v if isinstance(v, str) else v.get("name", "")
                if any(d["name"] == n for d in dims):
                    dim_names.append(n.upper())
                elif any(m["name"] == n for m in measures):
                    meas_names.append(n.upper())
        x = dim_names[0] if dim_names else (dims[0]["name"].upper() if dims else "CATEGORY")
        y = meas_names[0] if meas_names else (measures[0]["name"].upper() if measures else "VALUE")
        sql_list.append(
            f'  query(`SELECT "{x}", SUM("{y}") AS "{y}" FROM {query_target} '
            f'GROUP BY "{x}" ORDER BY "{y}" DESC LIMIT 200`).then(setData{i});'
        )

    fetch_block = "\n".join(sql_list)
    imports_str = ", ".join(sorted(used_components))
    fp_import = 'import FilterPanel from "@/components/FilterPanel";\n' if filter_widgets else ""

    return textwrap.dedent(f"""\
        "use client";
        import {{ useState, useEffect }} from "react";
        import {{ {imports_str} }} from "@/components/charts";
        {fp_import}import {{ query }} from "@/lib/snowflake";
        import {{ FilterState }} from "@/lib/types";

        export default function {_safe_var(name)}Dashboard() {{
          {state_inits}
          const [_filters, setFilters] = useState<FilterState>({{}});

          useEffect(() => {{
            {fetch_block}
          }}, [_filters]);

          return (
            <div className="flex h-full">
              {"<FilterPanel onChange={f => setFilters(prev => ({ ...prev, ...f }))} />" if filter_widgets else ""}
              <div className="flex-1 p-6 overflow-y-auto">
                <h1 className="text-2xl font-bold text-slate-900 mb-6">{name}</h1>
                <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
        {"".join(chart_blocks)}
                </div>
              </div>
            </div>
          );
        }}
    """)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate(
    inventory_path: str,
    output_dir: str,
    app_name: str = "BI Suite",
    semantic_view: str | None = None,
    embed_agent: str | None = None,
    dashboards_filter: list[str] | None = None,
) -> dict[str, Any]:
    """
    Generate a full Next.js + ECharts project at output_dir.
    Returns a structured result dict.
    """
    with open(inventory_path) as fh:
        inventory = json.load(fh)

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    dashboards = inventory.get("dashboards", [])
    if dashboards_filter:
        dashboards = [d for d in dashboards if d.get("name") in dashboards_filter]
    if not dashboards:
        dashboards = [{"name": "Dashboard", "sheets": inventory.get("worksheets", [])}]

    tables = inventory.get("tables", [])
    primary_table = ""
    if tables:
        t = tables[0]
        db = inventory.get("snowflake_target", {}).get("database", "DB")
        sch = inventory.get("snowflake_target", {}).get("schema", "SCHEMA")
        tname = t.get("snowflake_name") or t.get("name", "TABLE")
        primary_table = f"{db}.{sch}.{tname}"

    raw_filters = inventory.get("parameters", []) or inventory.get("filters", [])
    filter_widgets = infer_filter_widgets(raw_filters) if raw_filters else []

    generated: list[dict] = []

    def write(rel: str, content: str) -> None:
        p = out / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8")
        generated.append({"path": str(p)})

    # Root config files
    write("app.yml",               _gen_app_yml(app_name))
    write("package.json",          _gen_package_json(app_name))
    write("tailwind.config.ts",    _gen_tailwind_config())
    write("tsconfig.json",         _gen_tsconfig())

    # Source files
    write("src/app/globals.css",   _gen_globals_css())
    write("src/lib/snowflake.ts",  _gen_snowflake_lib())
    write("src/lib/types.ts",      _gen_types())

    # Chart components
    write("src/components/charts/BarChart.tsx",    _gen_bar_chart_tsx())
    write("src/components/charts/LineChart.tsx",   _gen_line_chart_tsx())
    write("src/components/charts/AreaChart.tsx",   _gen_area_chart_tsx())
    write("src/components/charts/PieChart.tsx",    _gen_pie_chart_tsx())
    write("src/components/charts/ScatterChart.tsx",_gen_scatter_chart_tsx())
    write("src/components/charts/MetricCard.tsx",  _gen_metric_card_tsx())
    write("src/components/charts/DataTable.tsx",   _gen_data_table_tsx())
    write("src/components/charts/index.ts",        _gen_charts_index())

    # Optional components
    write("src/components/FilterPanel.tsx", _gen_filter_panel_tsx(filter_widgets))
    if embed_agent:
        write("src/components/AgentChat.tsx", _gen_agent_chat_tsx(embed_agent))

    # App layout + home
    dash_names = [d.get("name", "") for d in dashboards]
    write("src/app/layout.tsx", _gen_layout_tsx(app_name, dash_names, embed_agent))
    write("src/app/page.tsx",   _gen_home_page_tsx(dash_names))

    # Dashboard pages
    for dash in dashboards:
        slug = _slugify(dash.get("name", "dashboard"))
        page_content = _gen_dashboard_page_tsx(dash, inventory, primary_table, semantic_view)
        write(f"src/app/dashboard/{slug}/page.tsx", page_content)

    return {
        "status": "ok",
        "command": "generate-react",
        "output_dir": output_dir,
        "app_name": app_name,
        "generated_files": generated,
        "dashboard_count": len(dashboards),
        "file_count": len(generated),
        "embed_agent": embed_agent,
        "semantic_view": semantic_view,
        "next_steps": [
            f"cd {output_dir} && npm install",
            "snow app deploy  # via snowflake-apps skill",
        ],
    }
