"""
bim_ui — enterprise dashboard component kit for Streamlit-in-Snowflake.

Generated by the bi-modernization skill. Targets the SiS container runtime
(Streamlit 1.50+, PyPI packages, cross-session caching).

The kit exists to make one class of problem impossible rather than caught late:
inconsistent number formatting, clipped chart labels, colors that mean two
different things, tables you cannot sort, and panels that render blank when a
filter excludes everything.

Layout of the kit:

    theme       semantic color roles, palette resolution, WCAG auditing
    fmt         one formatting code path (KPI, axis, tooltip, grid cell agree)
    states      deliberate empty / error / loading / no-permission states
    filters     cross-filter store with exclude-self, URL state, drill-down
    charts      chart builders with reference lines and computed label headroom
    grid        native st.dataframe wrapper with column_config and export
    kpi         KPI cards with sparkline and progress-vs-target
    provenance  freshness / row count / source lineage banner

Usage sketch:

    from bim_ui import theme, fmt, filters, charts, grid, kpi, provenance

    palette = theme.resolve_palette(visuals)
    formats = fmt.FormatRegistry().load_visuals(visuals)
    ctx = UIContext(palette=palette, formats=formats)
"""

from __future__ import annotations

from dataclasses import dataclass, field

from . import charts as charts
from . import compat as compat
from . import filters as filters
from . import fmt as fmt
from . import grid as grid
from . import kpi as kpi
from . import provenance as provenance
from . import states as states
from . import theme as theme

__all__ = [
    "UIContext",
    "apply_theme",
    "charts",
    "compat",
    "filters",
    "fmt",
    "grid",
    "kpi",
    "provenance",
    "states",
    "theme",
    "__version__",
]

__version__ = "1.0.0"


@dataclass
class UIContext:
    """Shared rendering context threaded through every kit component.

    Passing one object rather than loose palette/format arguments is what keeps
    a chart, a KPI card, and a grid cell from disagreeing about how the same
    field should look.
    """

    palette: "theme.Palette" = field(default_factory=theme.resolve_palette)
    formats: "fmt.FormatRegistry" = field(default_factory=fmt.FormatRegistry)
    demo_mode: bool = False

    # Attainment thresholds. Carried on the context so a dashboard can define
    # "on track" once instead of each chart inventing its own cutoffs.
    good_at: float = 0.95
    warn_at: float = 0.80

    @classmethod
    def from_visuals(
        cls,
        visuals: dict | None = None,
        *,
        brand_colors=None,
        background: str | None = None,
        demo_mode: bool = False,
        **kwargs,
    ) -> "UIContext":
        """Build a context from extract-visuals output."""
        return cls(
            palette=theme.resolve_palette(
                visuals, brand_colors=brand_colors, background=background
            ),
            formats=fmt.FormatRegistry().load_visuals(visuals),
            demo_mode=demo_mode,
            **kwargs,
        )

    def status_color(self, ratio: float) -> str:
        return self.palette.status(ratio, good_at=self.good_at, warn_at=self.warn_at)

    def fmt_field(self, field_name: str, value, dtype=None) -> str:
        return self.formats.render(field_name, value, dtype)

    def contrast_report(self) -> list["theme.ContrastFinding"]:
        return theme.audit_contrast(self.palette)


def apply_theme(ctx: "UIContext") -> None:
    """Inject the kit's base CSS. Call once, immediately after set_page_config.

    Only covers what .streamlit/config.toml cannot express (the header band, KPI
    cards, chips, provenance strip). Widget and dataframe theming comes from
    config.toml, which is more reliable across Streamlit versions than CSS that
    targets internal test IDs.
    """
    import streamlit as st

    st.markdown(theme.base_css(ctx.palette), unsafe_allow_html=True)
